helmCharts:
  - name: kro
    repo: oci://registry.k8s.io/kro/charts
    version: 0.7.1
    releaseName: kro
    namespace: kro-system
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - namespace.yaml
