apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-deep-research
  namespace: local-deep-research
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-deep-research
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-deep-research
    spec:
      containers:
      - name: local-deep-research
        # Releases are broken?
        image: localdeepresearch/local-deep-research:amd64-9621af15d216a0fabd155a9ecc7d7e9cac37a250
        env:
        - name: LDR_APP_DEBUG
          value: "true"
        - name: LDR_DATA_DIR
          value: /data
        - name: LDR_LLM_OLLAMA_URL
          value: http://ollama.ollama.svc.cluster.local:11434
        - name: LDR_LLM_PROVIDER
          value: ollama
        - name: LDR_LLM_MODEL
          value: "gemma3:4b-it-qat"
        - name: LDR_SEARCH_ENGINE_WEB_SEARXNG_DEFAULT_PARAMS_INSTANCE_URL
          value: http://searxng.searxng.svc.cluster.local:8080
        ports:
        - name: ldr
          containerPort: 5000
        volumeMounts:
        - name: local-deep-research-data
          mountPath: /data
      volumes:
      - name: local-deep-research-data
        persistentVolumeClaim:
          claimName: local-deep-research-data-nfs-pvc