apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: local-deep-research
  name: local-deep-research
  namespace: local-deep-research
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: local-deep-research
      port: 5000
      protocol: TCP
      targetPort: local-deep-research
  selector:
    app.kubernetes.io/name: local-deep-research
  sessionAffinity: None
  type: ClusterIP