resources:
- ./providers/crossplane-contrib/crossplane-contrib-provider-aws.yaml
- ./providers/crossplane-contrib/crossplane-contrib-provider-aws-config.yaml
- ./providers/crossplane-contrib/crossplane-contrib-provider-gcp.yaml
- ./providers/crossplane-contrib/crossplane-contrib-provider-gcp-config.yaml