resources:
  - ./providers/crossplane-contrib/crossplane-contrib-provider-aws.yaml
  - ./providers/crossplane-contrib/crossplane-contrib-provider-aws-config.yaml
  - ./providers/upbound/upbound-provider-aws-cloudfront.yaml
  - ./providers/upbound/upbound-provider-aws-s3.yaml
  - ./providers/upbound/upbound-provider-aws-acm.yaml
  - ./providers/upbound/upbound-provider-aws-config.yaml
  - ./providers/upbound/upbound-provider-aws-iam.yaml
