apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-notebook
  namespace: open-notebook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: open-notebook
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-notebook
    spec:
      containers:
      - name: open-notebook
        # renovate: datasource=github-releases depname=lfnovo/open-notebook versioning=docker
        image: ghcr.io/lfnovo/open-notebook:1.2.1-single
        env:
        - name: API_URL
          value: https://open-notebook.crobasaurusrex.ryanbeales.com
        - name: OLLAMA_API_BASE
          value: http://ollama.ollama.svc.cluster.local:11434
        # SurrealDB configuration
        - name: SURREAL_URL
          value: ws://localhost:8000/rpc
        - name: SURREAL_USER
          value: root
        - name: SURREAL_PASSWORD
          value: root
        - name: SURREAL_NAMESPACE
          value: open_notebook
        - name: SURREAL_DATABASE
          value: production
        ports:
        - name: nextjs
          containerPort: 8502
        volumeMounts:
        - name: notebook-storage
          mountPath: /app/data
        - name: surrealdb-storage
          mountPath: /mydata

      volumes:
      - name: notebook-storage
        persistentVolumeClaim:
          claimName: open-notebook-notebook-nfs-pvc
      - name: surrealdb-storage
        persistentVolumeClaim:
          claimName: open-notebook-surrealdb-nfs-pvc