apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ollama-fast
  name: ollama-fast
  namespace: ollama
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: ollama
      port: 11434
      protocol: TCP
      targetPort: ollama
  selector:
    app.kubernetes.io/name: ollama-fast
  sessionAffinity: None
  type: ClusterIP